name: Build QEMU i386.js and i386.wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.39' # Change to a valid version

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-pip \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          libpixman-1-dev \
          cmake \
          automake \
          libtool

    - name: Verify Emscripten installation
      run: |
        source $EMSDK/emsdk_env.sh
        emcc --version

    - name: Clone QEMU repository
      run: |
        git clone --depth 1 --branch v7.2.0 https://github.com/qemu/qemu.git qemu-src
        cd qemu-src
        git submodule init
        git submodule update --recursive

    - name: Configure environment
      run: |
        source $EMSDK/emsdk_env.sh
        export CC=emcc
        export CXX=em++
        export AR=emar
        export RANLIB=emranlib
        export CFLAGS="-O2 -s WASM=1 -s FORCE_FILESYSTEM=1 -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1"
        export LDFLAGS="-O2 -s WASM=1 -s FORCE_FILESYSTEM=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORTED_RUNTIME_METHODS=['FS','callMain']"

    - name: Configure QEMU
      run: |
        cd qemu-src
        ./configure \
          --target-list=i386-softmmu \
          --disable-docs \
          --disable-system \
          --disable-user \
          --disable-tools \
          --disable-guest-agent \
          --disable-werror \
          --enable-debug \
          --cross-prefix=emscripten- \
          --host-cc="emcc" \
          --cc="emcc" \
          --cxx="em++" \
          --objcc="emcc" \
          --extra-cflags="$CFLAGS" \
          --extra-ldflags="$LDFLAGS"

    - name: Build QEMU
      run: |
        cd qemu-src
        make -j$(nproc)

    - name: Package artifacts
      run: |
        mkdir -p artifacts
        cp qemu-src/build/qemu-system-i386* artifacts/
        mv artifacts/qemu-system-i386 artifacts/i386.js
        mv artifacts/qemu-system-i386.wasm artifacts/i386.wasm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-i386-build
        path: artifacts/
