name: Build Android-Compatible QEMU WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.45'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git python3 \
          libglib2.0-dev libpixman-1-dev \
          ninja-build cmake \
          libnettle-dev libgnutls28-dev

    - name: Clone QEMU (v5.2.0 with Android patches)
      run: |
        git clone --depth 1 --branch v5.2.0 https://github.com/qemu/qemu.git qemu-src
        cd qemu-src
        git submodule update --init
        # Apply critical Android/WASM compatibility patches
        curl https://qemu.org/patches/android-wasm.patch | git apply -

    - name: Configure build
      run: |
        source $EMSDK/emsdk_env.sh
        cd qemu-src
        mkdir build && cd build
        emconfigure ../configure \
          --target-list=arm-softmmu \
          --disable-system \
          --disable-user \
          --disable-tools \
          --enable-debug \
          --extra-cflags="-s WASM=1 -s ASYNCIFY -s ALLOW_MEMORY_GROWTH=1" \
          --extra-ldflags="-s WASM=1 -s ASYNCIFY -s ALLOW_MEMORY_GROWTH=1"

    - name: Build QEMU
      run: |
        cd qemu-src/build
        emmake make -j$(nproc)

    - name: Prepare artifacts
      run: |
        mkdir -p artifacts
        cp qemu-src/build/qemu-system-arm* artifacts/
        # Rename for Android compatibility
        mv artifacts/qemu-system-arm artifacts/android-vm.js
        mv artifacts/qemu-system-arm.wasm artifacts/android-vm.wasm
        # Create loader HTML
        echo '<!DOCTYPE html>
        <script src="android-vm.js"></script>
        <script>
        Module = {
          onRuntimeInitialized: () => {
            console.log("Android VM ready");
          }
        };
        </script>' > artifacts/loader.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-qemu-vm
        path: artifacts/
