name: Upload to Appetize.io (Demo)

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download sample APK
      run: |
        wget https://github.com/appetize-io/example-apps/raw/master/android/app.apk

    - name: Upload to Appetize.io
      run: |
        curl -H "Authorization: Bearer tok_o3laoux75kpoudqemidnbxfvpq" \
             -F "file=@app.apk" \
             -F "platform=android" \
             https://api.appetize.io/v1/apps
