name: Build QEMU WASM for Android

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 90  # Extended timeout for complex build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.45'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git python3 \
          libglib2.0-dev libpixman-1-dev \
          ninja-build cmake meson \
          autoconf automake libtool \
          pkg-config gettext

    - name: Clone QEMU with WASM patches
      run: |
        git clone --depth 1 https://github.com/qemu/qemu.git qemu-src
        cd qemu-src
        # Apply minimal WASM compatibility patches
        curl -sL https://github.com/qemu/qemu/compare/master...wasm.patch | git apply -
        git submodule update --init --depth 1 dtc

    - name: Configure build environment
      run: |
        source $EMSDK/emsdk_env.sh
        export CC="emcc"
        export CXX="em++"
        export AR="emar"
        export RANLIB="emranlib"
        export CFLAGS="-O2 -s WASM=1 -s ASYNCIFY -s ALLOW_MEMORY_GROWTH=1 -s FORCE_FILESYSTEM=1"
        export LDFLAGS="$CFLAGS -s EXPORTED_RUNTIME_METHODS=['FS','callMain']"

    - name: Build minimal QEMU components
      run: |
        cd qemu-src
        ./configure \
          --disable-system \
          --disable-user \
          --disable-tools \
          --disable-docs \
          --disable-guest-agent \
          --disable-werror \
          --target-list=x86_64-softmmu \
          --extra-cflags="$CFLAGS" \
          --extra-ldflags="$LDFLAGS"
        
        make -j2 qemu-system-x86_64

    - name: Convert to WASM
      run: |
        cd qemu-src
        emcc -o qemu-wasm.js \
          *.o -lglib-2.0 -lpixman-1 \
          $LDFLAGS \
          -s EXPORTED_FUNCTIONS='["_main"]' \
          -s MODULARIZE=1

    - name: Package artifacts
      run: |
        mkdir -p artifacts
        cp qemu-src/qemu-wasm.js artifacts/
        cp qemu-src/qemu-wasm.wasm artifacts/
        echo '<!DOCTYPE html>
        <script src="qemu-wasm.js"></script>
        <script>
        Module = {
          onRuntimeInitialized: () => {
            FS.mkdir("/home");
            FS.mount(MEMFS, {}, "/home");
            console.log("QEMU WASM ready");
          }
        };
        </script>' > artifacts/loader.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-wasm-android
        path: artifacts/
