name: Build QEMU for Android WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      with:
        version: '3.1.45'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential git python3 \
          libglib2.0-dev libpixman-1-dev \
          ninja-build cmake meson \
          nettle-dev libgnutls28-dev \
          pkg-config gettext

    - name: Clone QEMU (with limited submodules)
      run: |
        git clone --depth 1 --branch v7.2.0 \
          https://github.com/qemu/qemu.git qemu-src
        cd qemu-src
        git submodule update --init --depth 1 \
          dtc ui/keycodemapdb

    - name: Configure environment
      run: |
        source $EMSDK/emsdk_env.sh
        export CC="emcc"
        export CXX="em++"
        export AR="emar"
        export RANLIB="emranlib"
        export CFLAGS="-O2 -s WASM=1 -s ASYNCIFY -s ALLOW_MEMORY_GROWTH=1"
        export LDFLAGS="$CFLAGS -s EXPORTED_RUNTIME_METHODS=['FS','callMain']"

    - name: Configure QEMU for i386 (supported target)
      run: |
        cd qemu-src
        mkdir build && cd build
        ../configure \
          --target-list=i386-softmmu \
          --disable-docs \
          --disable-system \
          --disable-user \
          --disable-tools \
          --disable-guest-agent \
          --disable-werror \
          --enable-debug \
          --disable-opengl \
          --disable-virglrenderer \
          --disable-gtk \
          --disable-sdl \
          --disable-vnc \
          --disable-slirp

    - name: Build QEMU
      run: |
        cd qemu-src/build
        make -j$(($(nproc)/2))

    - name: Post-process for WASM
      run: |
        cd qemu-src/build
        emcc -o qemu-system-i386.js \
          *.o -lglib-2.0 -lpixman-1 -lnettle \
          $LDFLAGS \
          -s EXPORTED_FUNCTIONS='["_main"]'

    - name: Package artifacts
      run: |
        mkdir -p artifacts
        cp qemu-src/build/qemu-system-i386.js artifacts/vm.js
        cp qemu-src/build/qemu-system-i386.wasm artifacts/vm.wasm
        echo '<!DOCTYPE html>
        <script src="vm.js"></script>
        <script>
        Module = {
          onRuntimeInitialized: () => console.log("VM ready")
        };
        </script>' > artifacts/loader.html

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-wasm-vm
        path: artifacts/
