name: Build QEMU to WebAssembly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip ninja-build cmake build-essential pkg-config

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.45

    - name: Clone QEMU (WebAssembly fork: v86)
      run: |
        git clone https://github.com/copy/v86.git
        cd v86
        git submodule update --init --recursive

    - name: Build QEMU to WebAssembly
      run: |
        cd v86
        make all
        mkdir -p ../dist
        cp v86.js v86.wasm ../dist/i360.js
        cp v86.wasm ../dist/i360.wasm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: i360-build
        path: dist/
