name: Build Android VM to WebAssembly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake ninja-build python3-pip curl qemu
        pip3 install --upgrade cmake

    - name: Set up Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "source $(pwd)/emsdk_env.sh" >> $GITHUB_ENV

    - name: Build .wasm and .js
      run: |
        source emsdk/emsdk_env.sh
        mkdir -p build
        cd build
        # Replace the line below with your actual source files and flags
        emcc ../src/main.c -O2 -s WASM=1 -s EXPORTED_FUNCTIONS='["_main"]' -o android-vm.js

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-vm-wasm-output
        path: |
          build/android-vm.js
          build/android-vm.wasm
