name: Upload to Appetize.io (Demo - From Repo)

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload to Appetize.io
      run: |
        curl -H "Authorization: Bearer tok_o3laoux75kpoudqemidnbxfvpq" \
             -F "file=@apk/app.apk" \
             -F "platform=android" \
             https://api.appetize.io/v1/apps
