name: Upload to Appetize.io (Demo)

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Download test APK
      run: |
        wget https://archive.org/download/github.com-delaroy-AndroidLoginAndRegistrationSystem_-_2019-12-15_07-20-23/app-debug.apk -O app.apk

    - name: Upload to Appetize.io
      run: |
        curl -H "Authorization: Bearer tok_o3laoux75kpoudqemidnbxfvpq" \
             -F "file=@app.apk" \
             -F "platform=android" \
             https://api.appetize.io/v1/apps
