name: Build Android-Compatible QEMU WASM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04 # Older OS for better compatibility
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v11
      with:
        version: '2.0.34' # Older but more stable for QEMU

    - name: Install dependencies
      run: |
        sudo apt-get install -y \
          build-essential git python3 \
          libglib2.0-dev libpixman-1-dev \
          ninja-build cmake

    - name: Clone QEMU
      run: |
        git clone --depth 1 --branch v5.2.0 \
          https://github.com/qemu/qemu.git qemu-src
        cd qemu-src
        git submodule update --init

    - name: Configure
      run: |
        source $EMSDK/emsdk_env.sh
        cd qemu-src
        mkdir build && cd build
        ../configure \
          --target-list=arm-softmmu,i386-softmmu \
          --disable-system --disable-user \
          --disable-tools --disable-guest-agent \
          --enable-debug \
          --cc=emcc --cxx=em++ \
          --ar=emar --objcc=emcc \
          --extra-cflags="-s WASM=1 -s ASYNCIFY" \
          --extra-ldflags="-s WASM=1 -s ASYNCIFY"

    - name: Build
      run: |
        cd qemu-src/build
        make -j4 # Reduced parallelism for stability

    - name: Package
      run: |
        mkdir artifacts
        cp qemu-src/build/qemu-system-{arm,i386}* artifacts/
        for arch in arm i386; do
          [ -f "artifacts/qemu-system-$arch" ] && 
            mv "artifacts/qemu-system-$arch" "artifacts/$arch.js"
          [ -f "artifacts/qemu-system-$arch.wasm" ] && 
            mv "artifacts/qemu-system-$arch.wasm" "artifacts/$arch.wasm"
        done

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: qemu-android-vm
        path: artifacts/
