name: Build QEMU i386.js and i386.wasm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3 \
          python3-pip \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          libpixman-1-dev \
          cmake \
          emscripten

    - name: Configure and build QEMU for i386
      run: |
        mkdir build
        cd build
        emconfigure ../configure \
          --target-list=i386-softmmu \
          --disable-docs \
          --disable-system \
          --disable-user \
          --disable-tools \
          --disable-guest-agent \
          --disable-werror \
          --enable-debug
        emmake make -j$(nproc)

    - name: Copy artifacts
      run: |
        mkdir -p artifacts
        cp build/qemu-system-i386.js artifacts/i386.js
        cp build/qemu-system-i386.wasm artifacts/i386.wasm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-i386-build
        path: artifacts/
